const dot = {
  PANCAKESWAP: new Set([
    'PANCAKESWAP-DOT-CAKE',
    'PANCAKESWAP-DOT-BUNNY',
    'PANCAKESWAP-DOT-REEF',
    'PANCAKESWAP-DOT-wBNB',
    'PANCAKESWAP-DOT-CTK',
    'PANCAKESWAP-DOT-XVS',
    'PANCAKESWAP-DOT-BUSD',
    'PANCAKESWAP-DOT-ETH',
    'PANCAKESWAP-DOT-ADA',
    'PANCAKESWAP-DOT-BURGER',
  ]),
  APESWAP: new Set(['APESWAP-DOT-wBNB', 'APESWAP-DOT-BUSD', 'APESWAP-DOT-ETH']),
  JULSWAP: new Set(['JULSWAP-DOT-wBNB', 'JULSWAP-DOT-BUSD']),
  BAKERYSWAP: new Set([
    'BAKERYSWAP-DOT-wBNB',
    'BAKERYSWAP-DOT-BUSD',
    'BAKERYSWAP-DOT-BETH',
    'BAKERYSWAP-DOT-USDT',
    'BAKERYSWAP-DOT-BAKE',
  ]),
  PANTHERSWAP: new Set([
    'PANTHERSWAP-DOT-wBNB',
    'PANTHERSWAP-DOT-BUSD',
    'PANTHERSWAP-DOT-ETH',
    'PANTHERSWAP-DOT-ADA',
  ]),
};

module.exports = dot;
